In [2]:
# Libraries
import numpy as np

In [79]:
# Reading the data file
f = open('new.txt')
lines = f.readlines()
result = []
for line in lines:
    # split the data into two arrays
    result.append(line.split(' '))
f.close

<function TextIOWrapper.close()>

In [81]:
# Creating A
a = result[:7]
A = np.array(a, dtype='int32')
A

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [4, 5, 6, 1, 2, 3, 4, 6],
       [4, 5, 6, 1, 2, 3, 4, 6],
       [4, 5, 6, 1, 2, 3, 4, 6],
       [4, 5, 6, 1, 2, 3, 4, 6],
       [4, 5, 6, 1, 2, 3, 4, 6],
       [4, 5, 6, 1, 2, 3, 4, 6]])

In [106]:
A.shape

(7, 8)

In [85]:
# Creating B
b = result[9:17]
B = np.array(b, dtype='int32')
B

array([[5, 6, 3, 4, 5, 6, 7],
       [5, 6, 3, 4, 5, 6, 7],
       [5, 6, 3, 4, 5, 6, 7],
       [5, 6, 3, 4, 5, 6, 7],
       [5, 6, 3, 4, 5, 6, 7],
       [5, 6, 3, 4, 5, 6, 7],
       [5, 6, 3, 4, 5, 6, 7],
       [5, 6, 3, 4, 5, 6, 7]])

In [107]:
B.shape

(8, 7)

In [112]:
# Finding N the maximun of the value of r1,c1 and r2,c2
r1,c1 = A.shape
r2,c2 = B.shape
N = max(r1,c1,r2,c2)
N

8

In [88]:
# Padding step (make each matrix N*N) by adding zeros 
Ax = np.zeros((N,N))
By = np.zeros((N,N))

def new_mtxs(a,b, n):
    
    shape = np.shape(a)
    Ax[:shape[0],:shape[1]] = a

    shape = np.shape(b)
    By[:shape[0],:shape[1]] = b
    
    return Ax, By
    

In [89]:
new_mtxs(A,B,N)

(array([[1., 2., 3., 4., 5., 6., 7., 8.],
        [4., 5., 6., 1., 2., 3., 4., 6.],
        [4., 5., 6., 1., 2., 3., 4., 6.],
        [4., 5., 6., 1., 2., 3., 4., 6.],
        [4., 5., 6., 1., 2., 3., 4., 6.],
        [4., 5., 6., 1., 2., 3., 4., 6.],
        [4., 5., 6., 1., 2., 3., 4., 6.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([[5., 6., 3., 4., 5., 6., 7., 0.],
        [5., 6., 3., 4., 5., 6., 7., 0.],
        [5., 6., 3., 4., 5., 6., 7., 0.],
        [5., 6., 3., 4., 5., 6., 7., 0.],
        [5., 6., 3., 4., 5., 6., 7., 0.],
        [5., 6., 3., 4., 5., 6., 7., 0.],
        [5., 6., 3., 4., 5., 6., 7., 0.],
        [5., 6., 3., 4., 5., 6., 7., 0.]]))

In [90]:
Ax

array([[1., 2., 3., 4., 5., 6., 7., 8.],
       [4., 5., 6., 1., 2., 3., 4., 6.],
       [4., 5., 6., 1., 2., 3., 4., 6.],
       [4., 5., 6., 1., 2., 3., 4., 6.],
       [4., 5., 6., 1., 2., 3., 4., 6.],
       [4., 5., 6., 1., 2., 3., 4., 6.],
       [4., 5., 6., 1., 2., 3., 4., 6.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [91]:
By

array([[5., 6., 3., 4., 5., 6., 7., 0.],
       [5., 6., 3., 4., 5., 6., 7., 0.],
       [5., 6., 3., 4., 5., 6., 7., 0.],
       [5., 6., 3., 4., 5., 6., 7., 0.],
       [5., 6., 3., 4., 5., 6., 7., 0.],
       [5., 6., 3., 4., 5., 6., 7., 0.],
       [5., 6., 3., 4., 5., 6., 7., 0.],
       [5., 6., 3., 4., 5., 6., 7., 0.]])

In [75]:
# implementation Strassen's matrix multiplication algorithm  
def split(matrix):
    """
    Splits a given matrix into quarters.
    Input: nxn matrix
    Output: tuple containing 4 n/2 x n/2 matrices corresponding to a, b, c, d
    """
    row, col = matrix.shape
    row2, col2 = row//2, col//2
    return matrix[:row2, :col2], matrix[:row2, col2:], matrix[row2:, :col2], matrix[row2:, col2:]

# x and y are matrices we are going to multiplying them by using the Strassen Algorithm to reduce the cost of Multiplication of matrices:
def strassen(x, y):
    """
    Computes matrix product by divide and conquer approach, recursively.
    Input: nxn matrices x and y
    Output: nxn matrix, product of x and y
    """
  
    # Base case when size of matrices is 1x1
    if len(x) == 1:
        return x * y
  
    # Splitting the matrices into quadrants. This will be done recursively
    # untill the base case is reached.
    a, b, c, d = split(x)
    e, f, g, h = split(y)
  
    # Computing the 7 products, recursively (p1, p2...p7), these P's are submatrices 
    # each of them has x and y so this why we are using the same function we built which is stranssen
    p1 = strassen(a, f - h)  
    p2 = strassen(a + b, h)        
    p3 = strassen(c + d, e)        
    p4 = strassen(d, g - e)        
    p5 = strassen(a + d, e + h)        
    p6 = strassen(b - d, g + h)  
    p7 = strassen(a - c, e + f)  
  
    # Computing the values of the 4 quadrants of the final matrix c
    c11 = p5 + p4 - p2 + p6  
    c12 = p1 + p2           
    c21 = p3 + p4            
    c22 = p1 + p5 - p3 - p7  
  
    # Combining the 4 quadrants into a single matrix by stacking horizontally and vertically.
    c = np.vstack((np.hstack((c11, c12)), np.hstack((c21, c22)))) 
  
    return c

In [92]:
strassen(Ax,By)

array([[180., 216., 108., 144., 180., 216., 252.,   0.],
       [155., 186.,  93., 124., 155., 186., 217.,   0.],
       [155., 186.,  93., 124., 155., 186., 217.,   0.],
       [155., 186.,  93., 124., 155., 186., 217.,   0.],
       [155., 186.,  93., 124., 155., 186., 217.,   0.],
       [155., 186.,  93., 124., 155., 186., 217.,   0.],
       [155., 186.,  93., 124., 155., 186., 217.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.]])

In [185]:
# Implemention of the classical matrix multiplication algorithm
def classical_multiplication(X,Y,n):
    result = np.zeros((n,n))
    # iterate through rows of X
    for i in range(len(X)):
       # iterate through columns of Y
       for j in range(len(Y[0])):
           # iterate through rows of Y
           for k in range(len(Y)):
               result[i][j] += X[i][k] * Y[k][j]

    for r in result:
       print(r)

In [186]:
classical_multiplication(Ax,By, 8)

[180. 216. 108. 144. 180. 216. 252.   0.]
[155. 186.  93. 124. 155. 186. 217.   0.]
[155. 186.  93. 124. 155. 186. 217.   0.]
[155. 186.  93. 124. 155. 186. 217.   0.]
[155. 186.  93. 124. 155. 186. 217.   0.]
[155. 186.  93. 124. 155. 186. 217.   0.]
[155. 186.  93. 124. 155. 186. 217.   0.]
[0. 0. 0. 0. 0. 0. 0. 0.]


### Finding the difference in excuting time between the calssical matrix multiplication and Stranssen multiplication algorithm:

In [99]:
# Classical matrix multiplication
import time 
c_startTime = time.time()
classical_multiplication(Ax,By, 8)
c_endTime = time.time()
c_exutingTime = c_endTime - c_startTime
print(c_exutingTime)

[180. 216. 108. 144. 180. 216. 252.   0.]
[155. 186.  93. 124. 155. 186. 217.   0.]
[155. 186.  93. 124. 155. 186. 217.   0.]
[155. 186.  93. 124. 155. 186. 217.   0.]
[155. 186.  93. 124. 155. 186. 217.   0.]
[155. 186.  93. 124. 155. 186. 217.   0.]
[155. 186.  93. 124. 155. 186. 217.   0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
0.010552406311035156


In [100]:
# Stranssen Algorithm
s_startTime = time.time()
strassen(Ax,By)
s_endTime = time.time()
s_exutingTime = s_endTime - s_startTime
print(s_exutingTime)

0.008523225784301758


## Question2

In [103]:
# My_studentID = Y3200009
sid = 3200009

# Modes
mode10 = sid%10
print(mode10)

mode100 = sid%100
print(mode100)

mode1000 = sid%1000
print(mode1000)

9
9
9


In [105]:
# The modulus are all equal 9 and as I understood the question, I just want to compare between two matrices one of them I will generat it randomly with size 9*9 from modulus and the another one I will 
# generat it with big size 100*100 to see clearly the differnce in time excuting between them.

# Creating a random matrix size 9*9 and the values less than 10000
mtx1 = np.random.randint(1, 10000, (mode10,mode10))
mtx1

array([[8703, 9963, 7236, 5505, 3087,  543, 6587, 4749, 1451],
       [8653, 7759, 6696, 8416, 7659, 7223,    4, 2253, 6158],
       [6272, 4143, 7323, 7052, 5080, 9635, 1781,  692, 1401],
       [ 708, 1959, 5048, 1776,  642, 1630, 8356, 4562, 9063],
       [6719, 8690, 5538, 2964, 4098, 7118, 8420,  422, 9335],
       [5537,  963, 5624,  478, 6403, 8503, 9044, 9173, 1114],
       [8957, 9395, 2250, 9464, 6478, 5913, 9444, 5357, 1537],
       [7579, 9183, 3011, 9673, 4411, 7789, 9818, 2303, 4138],
       [7062, 5926, 3079, 3770, 9805, 5152, 4093,  480, 5341]])

In [311]:
mtx2 = np.random.randint(1, 10000, (32,32))
mtx2

array([[1396, 7894, 5638, ..., 9831, 4443, 1923],
       [5200, 5972, 7594, ..., 3548, 6947, 3089],
       [7578,  861, 1995, ..., 9083, 7109, 3422],
       ...,
       [ 248, 1002, 8724, ..., 5232, 2516, 2597],
       [3821, 2863, 3420, ..., 7254, 1871, 9699],
       [3666, 3338, 4447, ..., 3441, 7808, 4830]])

In [312]:
r1,c1 = mtx1.shape
r2,c2 = mtx2.shape
N2 = max(c1,r1,c2,r2)
N2

32

In [313]:
Am = np.zeros((N2,N2))
Bm = np.zeros((N2,N2))
def new_mts(a,b,N2):
    shape = np.shape(a)
    Am[:shape[0],:shape[1]] = a

    shape = np.shape(b)
    Bm[:shape[0],:shape[1]] = b

    return Am, Bm
new_mts(mtx1,mtx2,N2)

(array([[8703., 9963., 7236., ...,    0.,    0.,    0.],
        [8653., 7759., 6696., ...,    0.,    0.,    0.],
        [6272., 4143., 7323., ...,    0.,    0.,    0.],
        ...,
        [   0.,    0.,    0., ...,    0.,    0.,    0.],
        [   0.,    0.,    0., ...,    0.,    0.,    0.],
        [   0.,    0.,    0., ...,    0.,    0.,    0.]]),
 array([[1396., 7894., 5638., ..., 9831., 4443., 1923.],
        [5200., 5972., 7594., ..., 3548., 6947., 3089.],
        [7578.,  861., 1995., ..., 9083., 7109., 3422.],
        ...,
        [ 248., 1002., 8724., ..., 5232., 2516., 2597.],
        [3821., 2863., 3420., ..., 7254., 1871., 9699.],
        [3666., 3338., 4447., ..., 3441., 7808., 4830.]]))

In [314]:
Am

array([[8703., 9963., 7236., ...,    0.,    0.,    0.],
       [8653., 7759., 6696., ...,    0.,    0.,    0.],
       [6272., 4143., 7323., ...,    0.,    0.,    0.],
       ...,
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.],
       [   0.,    0.,    0., ...,    0.,    0.,    0.]])

In [315]:
Bm

array([[1396., 7894., 5638., ..., 9831., 4443., 1923.],
       [5200., 5972., 7594., ..., 3548., 6947., 3089.],
       [7578.,  861., 1995., ..., 9083., 7109., 3422.],
       ...,
       [ 248., 1002., 8724., ..., 5232., 2516., 2597.],
       [3821., 2863., 3420., ..., 7254., 1871., 9699.],
       [3666., 3338., 4447., ..., 3441., 7808., 4830.]])

In [316]:
Bm.shape

(32, 32)

In [317]:
Am.shape

(32, 32)

In [318]:
s_startTime = time.time()
strassen(Am,Bm)
s_endTime = time.time()
s_exutingTime = s_endTime - s_startTime
print(s_exutingTime)

0.21708989143371582


In [329]:
c_startTime = time.time()
classical_multiplication(Am, Bm, N2)
c_endTime = time.time()
c_exutingTime = c_endTime - c_startTime
print()
print("E_time = ", c_exutingTime)

[1.23986916e+08 2.60547128e+08 1.67720652e+08 2.10952352e+08
 1.44048716e+08 2.07888014e+08 1.70557199e+08 1.27921740e+08
 1.18867762e+08 2.04734154e+08 2.71049017e+08 1.14638949e+08
 1.31107008e+08 2.41694917e+08 1.52768107e+08 1.55372740e+08
 1.59537389e+08 1.45909415e+08 2.58213271e+08 1.80505387e+08
 1.36919296e+08 2.32257601e+08 2.45684641e+08 2.50025798e+08
 1.58716137e+08 1.12079589e+08 1.27146765e+08 1.99424899e+08
 1.50676635e+08 1.41270761e+08 1.30893302e+08 2.18569114e+08
 1.53480752e+08 1.62776569e+08 1.55292579e+08 1.54607534e+08
 1.59852046e+08 2.42898227e+08 2.17956791e+08 1.79453842e+08
 2.05331556e+08 1.82797339e+08 2.65396464e+08 2.01505924e+08
 1.89818931e+08 1.68600659e+08 2.12814255e+08 2.19914078e+08
 1.54530122e+08 9.29469870e+07 2.20434333e+08 1.70922552e+08
 1.36049507e+08 1.61139953e+08 2.10619811e+08 2.01835124e+08
 1.93076150e+08 2.46771869e+08 1.88997083e+08 1.30329707e+08
 2.08002245e+08 1.19711565e+08 1.54275642e+08 2.32607676e+08
 1.27813939e+08 2.019900

 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 

 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 

In [320]:
# for more understanding I took another two matrices with difference sizes
mtx1 = np.random.randint(1, 10000, (mode10,mode10))
mtx2 = np.random.randint(1, 10000, (256,256))

r1,c1 = mtx1.shape
r2,c2 = mtx2.shape
N2 = max(c1,r1,c2,r2)
N2

Am = np.zeros((N2,N2))
Bm = np.zeros((N2,N2))
def new_mts(a,b,N2):
    shape = np.shape(a)
    Am[:shape[0],:shape[1]] = a

    shape = np.shape(b)
    Bm[:shape[0],:shape[1]] = b

    return Am, Bm
new_mts(mtx1,mtx2,N2)

s_startTime = time.time()
strassen(Am,Bm)
s_endTime = time.time()
s_exutingTime = s_endTime - s_startTime
print(s_exutingTime)


c_startTime = time.time()
classical_multiplication(Am, Bm, N2)
c_endTime = time.time()
c_exutingTime = c_endTime - c_startTime
print()
print("E_time = ", c_exutingTime)

61.6343150138855
[1.23986916e+08 2.60547128e+08 1.67720652e+08 2.10952352e+08
 1.44048716e+08 2.07888014e+08 1.70557199e+08 1.27921740e+08
 1.18867762e+08 2.04734154e+08 2.71049017e+08 1.14638949e+08
 1.31107008e+08 2.41694917e+08 1.52768107e+08 1.55372740e+08
 1.59537389e+08 1.45909415e+08 2.58213271e+08 1.80505387e+08
 1.36919296e+08 2.32257601e+08 2.45684641e+08 2.50025798e+08
 1.58716137e+08 1.12079589e+08 1.27146765e+08 1.99424899e+08
 1.50676635e+08 1.41270761e+08 1.30893302e+08 2.18569114e+08
 1.53480752e+08 1.62776569e+08 1.55292579e+08 1.54607534e+08
 1.59852046e+08 2.42898227e+08 2.17956791e+08 1.79453842e+08
 2.05331556e+08 1.82797339e+08 2.65396464e+08 2.01505924e+08
 1.89818931e+08 1.68600659e+08 2.12814255e+08 2.19914078e+08
 1.54530122e+08 9.29469870e+07 2.20434333e+08 1.70922552e+08
 1.36049507e+08 1.61139953e+08 2.10619811e+08 2.01835124e+08
 1.93076150e+08 2.46771869e+08 1.88997083e+08 1.30329707e+08
 2.08002245e+08 1.19711565e+08 1.54275642e+08 2.32607676e+08
 1.2781

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 

In [327]:
print("Excuting time Strassen's Algorithms: ", s_exutingTime)
print("Excuting time Classical Algorithm: ",    c_exutingTime)

Excuting time Strassen's Algorithms:  61.6343150138855
Excuting time Classical Algorithm:  29.70825505256653


In [ ]:
# We can see clearly that the Strassen's algorithm for matrix multiplication is faster than the classical
# matrix multiplication algorithm. However, it's slower for extermely large matrices we can see that clearly in the last exapmles when the matrices size be more larger